config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"     #新規作成URLを/signupにするため
  resources :users do
    member do
      get :followings   #/users/:id/followingsというURLが生成される
      get :followers    #/users/:id/followersというURLが生成される
      get :likes        #/users/:id/likesというURLが生成される
    end
  end
  
  resources :posts, only: [:index, :new, :edit, :update, :create, :destroy]
  resources :relationships, only: [:create, :destroy] #フォロー／アンフォローできるようにする
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }                                        #インスタンスを保存する前に実行。文字を全て小文字に変換する。
    validates :name, presence: true, length: { maximum: 50 }                    #nameは空を許さず、長さは50文字以内
    validates :email, presence: true, length: { maximum: 255 },                 #emailは空を許さず、長さは255文字以内
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },   #アドレスが正しい形式になっているか確認している
                      uniqueness: { case_sensitive: false } #登録の重複を許さない。大文字と小文字を区別しない。
    
    
    mount_uploader :image, ImageUploader
    
    has_secure_password    #パスワード付きのモデルなので使用。usersテーブルにパスワードを保存する時暗号化される。
    
    has_many :posts, dependent: :destroy     #userから見てpostは複数。この関連付けにより投稿が紐付けになる。
    
    has_many :relationships, dependent: :destroy     #自分がたくさんのrelationshipsを持つよという意味
    
    has_many :followings, through: :relationships, source: :follow, dependent: :destroy  #自分は[followings]で[relationships]を介して[follow]と繋がるよという意味
    
    has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
    #[reverses_of_relationship]は12行目の[relationships]と名前がかぶるので、名前を変えて逆方向の自分は[relationships]をたくさん持つよと示している
    #[class_name: 'Relationship']は[reverses_of_relationship]というクラスが存在しないので[relationships]を参照すると示している
    #[foreign_key: 'follow_id']は自分はuser_idではなく、反対側にいるfollw_idだと示している
    
    has_many :followers, through: :reverses_of_relationship, source: :user, dependent: :destroy  #自分は[followers]で逆方法にいるから[reverses_of_relationship]を介して[user]と繋がるよという意味
    
    has_many :favorites, dependent: :destroy
    has_many :fav_posts, through: :favorites, source: :post, dependent: :destroy
    
    def follow(other_user)
      unless self == other_user #self には user.follow(other) を実行したとき user が代入される。
        self.relationships.find_or_create_by(follow_id: other_user.id)  #フォロー関係を保存(create = build + save)することができる
      end
    end
    
    def unfollow(other_user)    #フォローがあればアンフォローしている
      relationship = self.relationships.find_by(follow_id: other_user.id)
      relationship.destroy if relationship
    end
    
    def following?(other_user)
      self.followings.include?(other_user)    #self.followings によりフォローしている User 達を取得し、include?(other_user) によって other_user が含まれていないかを確認している。
    end
    
    def feed_posts   #タイムライン用
      Post.where(user_id: self.following_ids + [self.id])   #Post.where(user_id: フォローユーザ + 自分自身)となるPostを全て取得している
    end
    
    
    def favorite(other_post)
      unless self == other_post
        self.favorites.find_or_create_by(post_id: other_post.id)
      end
    end
    
    def unfavorite(other_post)
      favorite = self.favorites.find_by(post_id: other_post.id)
      favorite.destroy if favorite
    end
    
    def checkfavorite?(other_post)
      self.fav_posts.include?(other_post)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit] #ログインしていないと表示できないようにしている
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index     #ユーザー一覧ページ。ユーザーの一覧を取得
    @users = User.order(id: :desc).page(params[:page]).per(10)
  end

  def show      #ユーザー詳細ページ
    @user = User.find(params[:id])    #ユーザー個々のidを取得
    @posts = @user.posts.order(id: :desc).page(params[:page]) #投稿の一覧を取得
    counts(@user)
  end

  def new       #アカウント新規登録ページ。
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザーを登録しました。"
      session[:user_id] = @user.id #このコードを使ってログインしている状態にしてるので二行目のrequire_user_logged_inではじかれない。※自主学習
      redirect_to @user  #user_path(@user.id)を略している
    else
      flash[:danger] = "ユーザーの登録に失敗しました。"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id]) #編集するユーザを取得
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = '正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:success] = "退会しました。"
    redirect_to login_url
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page]).per(10)
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page]).per(10)
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @fav_posts = @user.fav_posts.page(params[:page])
    counts(@user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :image, :password, :password_confirmation)
  end
  
  def correct_user    #ユーザー編集ページがログインユーザーの物なのか確認している
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <% if user.image? %>
          <%= image_tag user.image.url, :size => '50x50', class: "mr-2 rounded" %>
        <% else %>
          <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <% end %> 
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1><%= @user.name %>の編集ページ</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="form-group">
        <%= f.label :image, "Profile Image" %>
        <%= f.file_field :image, class: 'form-control'  %>
      </div>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '変更', class: 'btn btn-info btn-block' %>
      <%= link_to  'アカウントを削除する', @user, method: :delete, class: "btn btn-danger btn-block",  data: { confirm: '本当に削除してよろしいですか？' }%>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body text-center">
        <% if @user.image? %>
          <%= image_tag @user.image.url %>
        <% else %>
          <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Photo Collection  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes  <span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body text-center">
        <% if @user.image? %>
          <%= image_tag @user.image.url %>
        <% else %>
          <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Photo Collection  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes  <span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>

app/views/users/index.html.erb
<%= render "users", users: @users %>

app/views/users/likes.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body text-center">
        <% if @user.image? %>
          <%= image_tag @user.image.url %>
        <% else %>
          <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
        <% end %>
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Photo Collection  <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes  <span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
    </ul>
    <%= render 'posts/posts', posts: @fav_posts %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>アカウント作成</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render "layouts/error_messages", model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '作成', class: 'btn btn-info btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body text-center">
        <% if @user.image? %>
          <%= image_tag @user.image.url %>
        <% else %>
          <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
        <% end %>
      </div>
    </div>
    <%= render "relationships/follow_button", user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Photo Collection <span class="badge badge-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>">Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>">Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>">Likes  <span class="badge badge-secondary"><%= @count_favorites %></span></a></li>
    </ul>
    <%= render 'posts/posts', posts: @posts %>
  </div>
</div>