config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"     #新規作成URLを/signupにするため
  resources :users do
    member do
      get :followings   #/users/:id/followingsというURLが生成される
      get :followers    #/users/:id/followersというURLが生成される
      get :likes        #/users/:id/likesというURLが生成される
    end
  end
  
  resources :posts, only: [:index, :new, :edit, :update, :create, :destroy]
  resources :relationships, only: [:create, :destroy] #フォロー／アンフォローできるようにする
  resources :favorites, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user  #postから見てuserは一人。この関連付けによりユーザーの紐付けなしでは投稿を保存できない。
  
  has_many :favorites, dependent: :destroy
  has_many :fav_users, through: :favorites, source: :user, dependent: :destroy
  
  validates :content, presence: true, length: { maximum: 255 }  #あとでimageのバリデーションも必要。
  validates :image, presence: true
  
  mount_uploader :image, ImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
      @posts = current_user.feed_posts.order(id: :desc).page(params[:page]) #feed_postsでタイムラインに対応させている
      #user.rbに定義されているfeed_postsメソッドを使えるのはcurrent_userユーザーの記述によってユーザーモデルを引き継いでいるから。
  end
  
  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '写真を投稿しました。'
      redirect_to user_path(current_user.id)
    else
      @posts = current_user.feed_posts.order(id: :desc).page(params[:page]) #feed_postsでタイムラインに対応させている
      flash.now[:danger] = '写真の投稿に失敗しました。'
      render :new
    end
  end
  
  def edit
    @post = Post.find(params[:id]) #編集する投稿を取得
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      flash[:success] = '更新されました'
      redirect_to user_path(current_user.id)
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '写真を削除しました。'
    redirect_back(fallback_location: root_path) #アクションが実行されたページに戻る指定
  end
  
  private
  
  def post_params
    params.require(:post).permit(:content, :image)
  end
  
  def correct_user    #投稿がログインユーザーの物なのか確認している
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to user_path(current_user.id)
    end
  end
end

app/views/posts/_posts.html.erb
<ul class="list-unstyled">
  <% posts.each do |post| %>
    <li class="media mb-3">
      <% if post.user.image? %>
        <%= image_tag post.user.image.url, :size => '50x50', class: "mr-2 rounded" %>
      <% else %>
        <img class="mr-2 rounded" src="<%= gravatar_url(post.user, { size: 50 }) %>" alt="">
      <% end %> 
      <div class="media-body ">
        <div>
          <%= link_to post.user.name, user_path(post.user) %> <span class="text-muted">posted at <%= post.created_at %></span>
        </div>
        <div class="row">
          <% if post.image? %>
            <div class="col-sm-5">
              <%= image_tag post.image.url %>
            </div>
          <% end %>
          <div class="col-sm-7">
            <p class="mb-10"><%= simple_format(post.content) %></p>
           
            <%= render "favorites/favorites_button", post: post %>
            
            <% if current_user == post.user %>
              <%= link_to "写真を編集する", edit_post_path(post), class: "btn btn-danger btn-sm" %>
            <% end %>
            
          </div>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate posts %>
</ul>

app/views/posts/edit.html.erb
<div class="text-center">
  <h1>投稿の編集</h1>
</div>
<div class="col-sm-4 offset-sm-4">
  <%= form_with(model: @post, local: true) do |f| %>
  <%= render "layouts/error_messages", model: f.object %>
  
    <div class="form-group">
        <%= f.label "画像をアップロード" %>
        <%= f.file_field :image, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label "コメント" %>
        <%= f.text_area :content, class: 'form-control', rows: 5 %>
    </div>
      <%= f.submit '編集を投稿する', class: 'btn btn-primary btn-block' %>
      <%= link_to "写真を削除する", @post, method: :delete, data: { confirm: "本当に削除してもよろしいですか？" }, class: "btn btn-danger btn-block" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<%= render 'posts/posts', posts: @posts %>

app/views/posts/new.html.erb
<div class="text-center">
  <h1>新規投稿</h1>
</div>
<div class="col-sm-4 offset-sm-4">
  <%= form_with(model: @post, local: true) do |f| %>
  <%= render "layouts/error_messages", model: f.object %>
    <div class="form-group">
        <%= f.label "画像をアップロード" %>
        <%= f.file_field :image, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label "コメント" %>
        <%= f.text_area :content, class: 'form-control', rows: 5 %>
    </div>
      <%= f.submit '写真を投稿する', class: 'btn btn-primary btn-block' %>
  <% end %>
</div>