config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"     #新規作成URLを/signupにするため
  resources :users do
    member do
      get :followings   #/users/:id/followingsというURLが生成される
      get :followers    #/users/:id/followersというURLが生成される
      get :likes        #/users/:id/likesというURLが生成される
    end
  end
  
  resources :posts, only: [:index, :new, :edit, :update, :create, :destroy]
  resources :relationships, only: [:create, :destroy] #フォロー／アンフォローできるようにする
  resources :favorites, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
        <ul class="mb-0">
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Photo Collection</a>
    <button class="navbar-toggler" type="button" date-toggle="collapse" date-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? #ログイン後の表示%>
          <li class="nav-item"><%= link_to '参加者', users_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '新規投稿', new_post_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Timeline', posts_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'マイページへ', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'マイページ編集', edit_user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "ログアウト",  logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else #ログイン前の表示%>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PhotoCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
    
  </head>
  
  <body>
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <%= render "layouts/flash_messages" %>  
      
      <%= yield %>
    </div>
  </body>
</html>